test: don't include multibyte filename in the repository
Because the error occurred in a non-UTF-8 environment:

    > gem install filerary
    Fetching: filerary-0.0.4.gem (100%)
    ERROR:  While executing gem ... (Encoding::InvalidByteSequenceError)
        "\x88" followed by "." on Windows-31J